---
# vim:ts=2:sw=2:et:ai:sts=2
name: Build distribution
on:
  # Only run when release is created in the master branch
  release:
    types: [created]
    branches: [master]
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    steps:
      - uses: actions/checkout@v3
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.10.1
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_ARCHS: auto64
          CIBW_BUILD: cp3* pp39*
          CIBW_PROJECT_REQUIRES_PYTHON: '>=3.8'
          CIBW_BEFORE_BUILD: pip3 install Cython
      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout source repository
        with:
            # You need to include this or setuptools_scm in GitHub runners won't detect the version
          fetch-depth: 0
      - uses: actions/setup-python@v4
      - name: Build sdist
        run: >
          pip3 install pkgconfig cython --upgrade &&
          python3 setup.py sdist
      - uses: actions/upload-artifact@v3
        name: Upload build artifacts
        with:
          path: dist/*.tar.gz
  publish:  # Run only on creating release for new tag
    name: 📦 Publish to PyPI
    runs-on: ubuntu-latest
    needs: check
    permissions:
      id-token: write
    environment: pypi
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - name: Download the sdist artifact
        uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
